sudo: false
language: node_js
node_js:
    - 12
cache:
    directories:
        - node_modules
script:
    - npm test
    - npm run coveralls
after_success:
    - bash <(curl -s https://codecov.io/bash)
